CREATE TABLE dbo.Articles(
	ArticleID BIGINT IDENTITY(-9223372036854775808, 1) NOT NULL
	, UserID BIGINT NOT NULL
	, CreatedDate SMALLDATETIME NOT NULL DEFAULT(GETUTCDATE())
	, Active BIT NOT NULL DEFAULT(1)
	, ArticleName NVARCHAR(100) NOT NULL
);
GO
ALTER TABLE dbo.Articles
ADD CONSTRAINT PK_ArticleID PRIMARY KEY NONCLUSTERED (ArticleID);
GO

