CREATE TABLE ORDERS.Menus(
	MenuID BIGINT IDENTITY(-9223372036854775808, 1)
	, UserID BIGINT NOT NULL 
	, MenuName NVARCHAR(100) NOT NULL 
	, CreatedDate SMALLDATETIME NOT NULL
	, LastUpdatedDate SMALLDATETIME NOT NULL
	, MenuCurrencyID INT NOT NULL
	, DeliveryEnabled BIT NOT NULL
 	, TakeOutEnabled BIT NOT NULL
	, DeliveryCharge MONEY NULL
	, TimeZoneID INT NOT NULL
	, Active BIT NOT NULL DEFAULT(1)
);
ALTER TABLE ORDERS.Menus ADD CONSTRAINT PK_ORDERS_Menus_MenuID PRIMARY KEY (MenuID);
GO
ALTER TABLE ORDERS.Menus ADD CONSTRAINT FK_ORDERS_Menus_UserID FOREIGN KEY (UserID) REFERENCES dbo.Users(UserID);
GO
ALTER TABLE ORDERS.Menus ADD CONSTRAINT FK_ORDERS_Menus_MenuCurrencyID FOREIGN KEY (MenuCurrencyID) REFERENCES dbo.Currencies(CurrencyID);
GO
ALTER TABLE ORDERS.Menus ADD CONSTRAINT FK_ORDERS_Menus_TimeZoneID FOREIGN KEY (TimeZoneID) REFERENCES TIMEZONE.Timezones(TimezoneID);
GO