
CREATE TABLE TIMEZONE.Timezones(
	TimezoneID INT IDENTITY(-2147483648, 1),
	TimezoneName NVARCHAR(100),
	LanguageID INT
);
ALTER TABLE TIMEZONE.Timezones ADD CONSTRAINT PK_TIMEZONE_Timezones_TimezoneID PRIMARY KEY (TimezoneID);
GO
ALTER TABLE TIMEZONE.Timezones ADD CONSTRAINT FK_TIMEZONE_Timezones_LanguageID FOREIGN KEY (LanguageID) REFERENCES dbo.Languages(LanguageID);
GO
