
CREATE TABLE dbo.Visits
(
	VisitRowID BIGINT NOT NULL IDENTITY(-9223372036854775808, 1),
	VisitDate DATE NOT NULL DEFAULT(GETUTCDATE()),
	VisitHour SMALLINT NOT NULL,
	VisitingSectionID SMALLINT NOT NULL,
	EntityID BIGINT NULL,
	CityID INT NULL,
	AmountOfVisits INT NOT NULL DEFAULT(1)
);

GO