USE [master]
GO
/****** Object:  Database [ReadWrite_Prod]    Script Date: 27/09/2017 11:53:22 p. m. ******/
CREATE DATABASE [ReadWrite_Prod] ON  PRIMARY 
( NAME = N'ReadWrite_Prod', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ReadWrite_Prod.mdf' , SIZE = 12544KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ReadWrite_Prod_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ReadWrite_Prod_log.LDF' , SIZE = 6272KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ReadWrite_Prod] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ReadWrite_Prod].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ReadWrite_Prod] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET ARITHABORT OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ReadWrite_Prod] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ReadWrite_Prod] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ReadWrite_Prod] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ReadWrite_Prod] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ReadWrite_Prod] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ReadWrite_Prod] SET  MULTI_USER 
GO
ALTER DATABASE [ReadWrite_Prod] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ReadWrite_Prod] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ReadWrite_Prod] SET  READ_WRITE 
GO
